url: http://www.surajitdutta.com
baseurl: #

# Site settings
title: Surajit Dutta - Software developer based in Germany
email: hello@surajitdutta.com
description: "My name is Surajit Dutta. I am a software developer and a passionate hobbyist of Machine Learning, Artificial Intelligence and Computer Vision.
I have previously worked in the field of Advanced Driver Assistance System (ADAS), Image Processing, Pattern Recognition, Unmanned Aerial Vehicle (UAV) and many more. My work includes developing intelligent software solutions. I
quickly adapt new technologies and start working on it. I like coding, cooking, playing piano, composing music and of course football."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 33ccff
  secondary: 33ccf1
  secondary-dark: 333

# # Team names, titles and social links
# people:
# - name: Patrick Ott
#   pic: 1
#   position: Machine Learning
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #
#
# - name: Patrick Ott
#   pic: 2
#   position: Object Detection
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #
#
# - name: Patrick Ott
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/surajroland
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url:
  # - title: bitbucket
  #   url: http://bitbucket.org/surajroland
  - title: linkedin
    url: https://de.linkedin.com/in/surajitdutta39/en
  - title: xing
    url: https://www.xing.com/profile/Surajit_Dutta2?sc_o=mxb_p
  - title: skype
    url: skype://suraj.roland?call
  - title: github
    url: http://github.com/surajroland
# Postal address (add as many lines as necessary)
address:
  - line: Spiegelberg 5
  - line: 88090 Imenstaad, Germany

# Build settings
markdown: kramdown
permalink: pretty
